FROM node:18
WORKDIR /app
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./index.js ./index.js
COPY ./connectMongo.js ./connectMongo.js
COPY ./roleModel.js ./roleModel.js
COPY ./rolePopulation.js ./rolePopulation.js
RUN npm ci
EXPOSE 3001
CMD ["node", "index.js"]